# Generated by Django 5.1 on 2024-08-09 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='opstmt.student')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cpmpany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='opstmt.company')),
            ],
        ),
        migrations.CreateModel(
            name='Opstmt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_sales', models.FloatField(default=0)),
                ('sales_domestic', models.FloatField(default=0)),
                ('sales_exports', models.FloatField(default=0)),
                ('others', models.FloatField(default=0)),
                ('total_sales', models.FloatField(default=0)),
                ('opening_stock_finished_goods', models.FloatField(default=0)),
                ('opening_stock_wip', models.FloatField(default=0)),
                ('opening_stock_rm', models.FloatField(default=0)),
                ('purchase_rm', models.FloatField(default=0)),
                ('power_fuel', models.FloatField(default=0)),
                ('direct_labour', models.FloatField(default=0)),
                ('repairs_maintenance', models.FloatField(default=0)),
                ('mfg_direct_expenses', models.FloatField(default=0)),
                ('depreciation', models.FloatField(default=0)),
                ('closing_stock_finished_goods', models.FloatField(default=0)),
                ('closing_stock_wip', models.FloatField(default=0)),
                ('closing_stock_rm', models.FloatField(default=0)),
                ('cost_of_sales', models.FloatField(default=0)),
                ('cost_of_production', models.FloatField(default=0)),
                ('gross_profit_loss', models.FloatField(default=0)),
                ('selling_adm_expenses', models.FloatField(default=0)),
                ('interest_fin_charges', models.FloatField(default=0)),
                ('operating_profit_loss', models.FloatField(default=0)),
                ('other_income_expenses', models.FloatField(default=0)),
                ('add_other_income', models.FloatField(default=0)),
                ('less_other_expenses', models.FloatField(default=0)),
                ('profit_before_tax', models.FloatField(default=0)),
                ('provision_for_taxes', models.FloatField(default=0)),
                ('net_profit_after_tax_loss', models.FloatField(default=0)),
                ('pbd_it', models.FloatField(default=0)),
                ('cash_accruals', models.FloatField(default=0)),
                ('dividend_drawings', models.FloatField(default=0)),
                ('retained_profit', models.FloatField(default=0)),
                ('net_cash_accrual', models.FloatField(default=0)),
                ('year', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='opstmt', to='opstmt.year')),
            ],
        ),
    ]
