# Generated by Django 5.1 on 2024-08-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opstmt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='year',
            old_name='cpmpany',
            new_name='company',
        ),
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
