# Generated by Django 5.1 on 2024-08-13 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opstmt', '0003_alter_year_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='FF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_profit_after_tax', models.FloatField(default=0.0)),
                ('depreciation', models.FloatField(default=0.0)),
                ('increase_in_capital_reserves', models.FloatField(default=0.0)),
                ('increase_in_term_loan', models.FloatField(default=0.0)),
                ('increase_in_other_term_liabilities', models.FloatField(default=0.0)),
                ('decrease_in_fixed_assets', models.FloatField(default=0.0)),
                ('decrease_in_non_current_assets', models.FloatField(default=0.0)),
                ('decrease_in_intangible_assets', models.FloatField(default=0.0)),
                ('total_long_term_sources', models.FloatField(default=0.0)),
                ('net_loss', models.FloatField(default=0.0)),
                ('increase_in_fixed_assets', models.FloatField(default=0.0)),
                ('increase_in_non_current_assets', models.FloatField(default=0.0)),
                ('increase_intangible_assets', models.FloatField(default=0.0)),
                ('decrease_in_term_loan', models.FloatField(default=0.0)),
                ('decrease_in_otl', models.FloatField(default=0.0)),
                ('dividend_payments', models.FloatField(default=0.0)),
                ('total_long_term_uses', models.FloatField(default=0.0)),
                ('long_term_surplus_deficit', models.FloatField(default=0.0)),
                ('increase_decrease_in_ca', models.FloatField(default=0.0)),
                ('inc_dec_in_cl_excl_bank_borrowing', models.FloatField(default=0.0)),
                ('increase_decrease_wc_gap', models.FloatField(default=0.0)),
                ('net_surplus_deficit', models.FloatField(default=0.0)),
                ('inc_dec_in_bank_borrowing', models.FloatField(default=0.0)),
                ('long_term_sources', models.FloatField(default=0.0)),
                ('long_term_uses', models.FloatField(default=0.0)),
                ('surplus_deficit', models.FloatField(default=0.0)),
                ('long_term_uses_vs_sources', models.FloatField(default=0.0)),
                ('increase_in_bank_borrowings', models.FloatField(default=0.0)),
                ('increase_in_sundry_creditors', models.FloatField(default=0.0)),
                ('increase_in_other_current_liabilities', models.FloatField(default=0.0)),
                ('decrease_in_inventory', models.FloatField(default=0.0)),
                ('decrease_in_receivables', models.FloatField(default=0.0)),
                ('decrease_in_other_current_assets', models.FloatField(default=0.0)),
                ('total_short_term_sources', models.FloatField(default=0.0)),
                ('decrease_in_bank_borrowings', models.FloatField(default=0.0)),
                ('decrease_in_sundry_creditors', models.FloatField(default=0.0)),
                ('decrease_in_ocl', models.FloatField(default=0.0)),
                ('increase_in_inventory', models.FloatField(default=0.0)),
                ('increase_in_receivables', models.FloatField(default=0.0)),
                ('increase_in_oca', models.FloatField(default=0.0)),
                ('total_short_term_uses', models.FloatField(default=0.0)),
                ('nwc_beginning_year', models.FloatField(default=0.0)),
                ('increase_decrease_in_nwc', models.FloatField(default=0.0)),
                ('nwc_end_year', models.FloatField(default=0.0)),
                ('long_term_sources_total', models.FloatField(default=0.0)),
                ('short_term_sources_total', models.FloatField(default=0.0)),
                ('total_sources', models.FloatField(default=0.0)),
                ('long_term_uses_total', models.FloatField(default=0.0)),
                ('short_term_uses_total', models.FloatField(default=0.0)),
                ('total_uses', models.FloatField(default=0.0)),
                ('tallied_difference', models.FloatField(default=0.0)),
                ('term_loan', models.FloatField(default=0.0)),
                ('increase_in_term_loan_final', models.FloatField(default=0.0)),
                ('decrease_in_term_loan_final', models.FloatField(default=0.0)),
                ('year', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ff', to='opstmt.year')),
            ],
        ),
    ]
